// Central config for search page static values

export const SEARCH_TABS = [
  { id: 'stores', label: 'Stores' },
  { id: 'categories', label: 'Categories' },
];

export const popularStores = [
  { name: "Amazon", logo: "🛒", color: "#FF9900" },
  { name: "Best Buy", logo: "🏷️", color: "#0046BE" },
  { name: "Target", logo: "🎯", color: "#CC0000" },
  { name: "Walmart", logo: "⭐", color: "#0071DC" },
  { name: "Macy's", logo: "🛍️", color: "#E21A2C" },
  { name: "eBay", logo: "📦", color: "#E53238" },
  { name: "Home Depot", logo: "🏠", color: "#F96302" },
  { name: "Newegg", logo: "💻", color: "#FF6600" },
];

export const allStores = [
  { name: "Amazon", count: 1234 },
  { name: "Apple Store", count: 89 },
  { name: "ASOS", count: 456 },
  { name: "Best Buy", count: 678 },
  { name: "B&H Photo", count: 234 },
  { name: "Costco", count: 345 },
  { name: "CVS", count: 123 },
  { name: "Dell", count: 267 },
  { name: "Dick's Sporting Goods", count: 189 },
  { name: "eBay", count: 890 },
  { name: "Etsy", count: 456 },
  { name: "Foot Locker", count: 234 },
  { name: "GameStop", count: 178 },
  { name: "Gap", count: 289 },
  { name: "Home Depot", count: 567 },
  { name: "HP", count: 198 },
  { name: "IKEA", count: 345 },
  { name: "JCPenney", count: 234 },
  { name: "Kohl's", count: 456 },
  { name: "Lenovo", count: 178 },
  { name: "Lowe's", count: 389 },
  { name: "Macy's", count: 567 },
  { name: "Newegg", count: 456 },
  { name: "Nike", count: 678 },
  { name: "Nordstrom", count: 345 },
  { name: "Old Navy", count: 234 },
  { name: "REI", count: 189 },
  { name: "Samsung", count: 345 },
  { name: "Sephora", count: 456 },
  { name: "Target", count: 789 },
  { name: "Ulta", count: 267 },
  { name: "Walmart", count: 987 },
  { name: "Wayfair", count: 345 },
  { name: "Zappos", count: 234 },
];

export const popularCategories = [
  { name: "Electronics", id: "electronics", icon: "📱", count: 2345 },
  { name: "Fashion", id: "fashion", icon: "👕", count: 1890 },
  { name: "Home & Kitchen", id: "home", icon: "🏠", count: 1456 },
  { name: "Beauty", id: "beauty", icon: "💄", count: 987 },
  { name: "Sports", id: "sports", icon: "⚽", count: 756 },
  { name: "Toys & Games", id: "toys", icon: "🎮", count: 567 },
  { name: "Grocery", id: "grocery", icon: "🛒", count: 432 },
  { name: "Automotive", id: "automotive", icon: "🚗", count: 321 },
];

export const allCategories = [
  { name: "Appliances", id: "appliances", count: 234 },
  { name: "Arts & Crafts", id: "arts", count: 189 },
  { name: "Automotive", id: "automotive", count: 321 },
  { name: "Baby", id: "baby", count: 456 },
  { name: "Beauty", id: "beauty", count: 987 },
  { name: "Books", id: "books", count: 234 },
  { name: "Cameras", id: "cameras", count: 178 },
  { name: "Cell Phones", id: "electronics", count: 567 },
  { name: "Clothing", id: "fashion", count: 1234 },
  { name: "Computers", id: "electronics", count: 456 },
  { name: "Electronics", id: "electronics", count: 2345 },
  { name: "Fashion", id: "fashion", count: 1890 },
  { name: "Fitness", id: "sports", count: 345 },
  { name: "Furniture", id: "home", count: 456 },
  { name: "Garden", id: "home", count: 234 },
  { name: "Grocery", id: "grocery", count: 432 },
  { name: "Health", id: "beauty", count: 567 },
  { name: "Home & Kitchen", id: "home", count: 1456 },
  { name: "Jewelry", id: "fashion", count: 234 },
  { name: "Kids", id: "kids", count: 345 },
  { name: "Luggage", id: "travel", count: 123 },
  { name: "Movies & TV", id: "entertainment", count: 234 },
  { name: "Music", id: "entertainment", count: 189 },
  { name: "Office", id: "office", count: 345 },
  { name: "Outdoors", id: "sports", count: 456 },
  { name: "Pet Supplies", id: "pets", count: 234 },
  { name: "Shoes", id: "fashion", count: 567 },
  { name: "Software", id: "electronics", count: 189 },
  { name: "Sports", id: "sports", count: 756 },
  { name: "Tools", id: "home", count: 345 },
  { name: "Toys & Games", id: "toys", count: 567 },
  { name: "Watches", id: "fashion", count: 234 },
];
